{% set name = "pydv" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://git.ligo.org/cds/software/pydv/archive/{{ version }}/pydv-{{ version }}.tar.gz
  sha256: 4844557a7eeadbc44575722fe61c255af18b081af5dda0eb33a10d6c1166661c 

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  entry_points:
    - pydv = pydv.__main__:main

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - gpstime
    - matplotlib-base
    - numpy
    - python >=3.6
    - python-nds2-client

test:
  imports:
    - pydv
    - pydv.bufferdict
    - pydv.const
    - pydv.plotting
    - pydv.util
  commands:
    - pydv --help

about:
  home: https://git.ligo.org/cds/pydv/
  dev_url: https://git.ligo.org/cds/pydv/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: NDS timeseries plotting utility
  description: |
    Python library for creating time series plots of LIGO data retrieved
    using the LIGO NDS services.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - jrollins
