{% set name = "pydv" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://git.ligo.org/cds/software/pydv/-/archive/{{ version }}/pydv-{{ version }}.tar.gz
  sha256: de77ed7436cccf62f2f01423cf034c084b72a53ab1f16b020e3bba0250349f56

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  entry_points:
    - pydv = pydv.__main__:main

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - gpstime
    - matplotlib-base
    - numpy
    - python >=3.6
    - python-nds2-client

test:
  imports:
    - pydv
    - pydv.bufferdict
    - pydv.const
    - pydv.plotting
    - pydv.util
  commands:
    - pydv --help

about:
  home: https://git.ligo.org/cds/software/pydv/
  dev_url: https://git.ligo.org/cds/software/pydv/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: NDS timeseries plotting utility
  description: |
    Python library for creating time series plots of LIGO data retrieved
    using the LIGO NDS services.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - jrollins
    - evonreis
