travis:
  secure:
    BINSTAR_TOKEN: aGjeWV2a/J5kztxNADtaZlpAymmGYpLUtH1GUp9qkew8TrC9FrKqpreLnfK0GWQ47FmMzcLSX/aCkK21gIQM8UoXtArbuMfmEhxVPvNrEdCBmXyWaW3TVRSEHW01wJmYKMM7uX+685/ADeRCq75/Zj6iI6YxnXBbQinF1uUM70t7BIE1wYnx9v76dLUR5uHBAh+4yhRlOmMfX/dwNu0ftEp8X4rgCW9g4riSqbIlcirkUwlNbEcXUe4yZf+/hhaBLCB0WwpnC7MVcQewEkhWfx9Lo5qhjHK/xO9SdeAiSyx4SPyIhLzUE4yzYBbY0lorTcv9EEtEkjXTjbq+Rii0T0VgjOD93un0hsPP5cILRrikWbpAF1NVqSwb++Sf7DEANCGCobEp8gGrPpsfPo9hQTZUMIYz7HAY9EL0hk3J/6VcO0V+sQiq4sR9aj9AwPoTOiGjBEfHXzogspu+qv/4RBo2eQ+fWFH8ijM9GG5veV+lrFD9oGYqXccGqDndc5qTEF02VPpXDPn/TftQyNJ4JdFb4vjKHmHoVPNMC2FS75x2cNOfyPfPqoD2tWaF9vHpxBA7qBFew6F/x6PpYRmV50Ppn7ctKuHnH/kTYQH1hdfA0f6uYOvWoafCUSn4XD69utzX3t48PGc2g7XDlMGk42+1vpoBPWf8wAXmJuBRNJI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
