travis:
  secure:
    BINSTAR_TOKEN: B1UhWz65l8dy1tr2GQY31doBtaP6BMTk0dgwyHRYMxTadMAYD0Vb5pQgglR3J282O78DBproOQu4qA+PqrQ34T9HH99lwaaQ5jx9noEC3xWP19vwwnNEU9UI7CBozrjNeZoLLnQuqAmHbfmMi9BGAfPbkB10IWaIhMcujVTYYwAI3iml73hh6QAc512DAs05qBou/94bvz0WRTNLlI5kDoOQTPetcRUmnZhpACQG7iZtlq8ev+hIKWlYTeBycn4D+zfiMWTh1b9Gp+aqhe1ongjlirp8a1zAsRvp8a104ETcN3TYchX22VHsTOW10JOyUKZ4JnTTaD7Z/IA+eKp84q6nL0PIAaP+oH9e8kD54klaLB/Q+4pax7Z1QySHxpZI4BEkfv0whW7aluUO5pMfniSKbvKj1PcrNwpixFECJS9n+WB3Xj/lZWR2Orvn6BvvF77T42RYYWvrNicy+ooe3zqGXkhtrx/3qzLzj0JjN5qG78BJyaEJcjm96Xe66Ov7XHGZr6smwW7rwa0C7wAF7gLUozETNsK/MKKZv6fApoirtQA5EG6nfBTfZnx2xPw8GxKBPf7wvBDxVkP3AdKoELRjTsxbzVJzAmjqEhtVFCOmRGyAgkK0TeBzm4AShX4zTi2cAgay2uLzn52s5Kto1cNR/wwJiCNmNvgH1VRTzqw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
